version: '3.8'

services:
# User Management Project 
  user-management-project:
     build:
       context: . 
       dockerfile: Dockerfile
     ports:
       - "8081:8081" 
     env_file:
       - ./.env
     volumes:
       - .:/app
       - /app/node_modules 
     networks:
       - my-network 

# Notification Service
  notification-service:
    build:
      context: . 
      dockerfile: notification-service/Dockerfile 
    ports:
      - "8082:8082"
    env_file:
      - ./notification-service/.env 
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - my-network 

networks:
  my-network:
    driver: bridge